services:
    postgres-db:
        image: 'postgres:latest'
        environment:
            - POSTGRES_DB=ypm-db
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USERNAME}
        ports:
            - '5432:5432'
        volumes:
            # DEV-NOTE: Used to initialize the DB schema, otherwise Liquibase migrations would fail
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ypm-db:/var/lib/postgresql/data

volumes:
    ypm-db:
