services:
    db:
        image: 'postgres:latest'
        environment:
            - POSTGRES_DB=ypm-db
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=$POSTGRES_USERNAME
        ports:
            - '5432:5432'
        volumes:
            - ypm-db:/var/lib/postgresql/data

volumes:
    ypm-db:
