spring:

  # Secret data
  config:
    import: classpath:application.secrets.yml

  # Spring specific
  application:
    name: youtube-playlist-manager

# Custom
youtube:
  application:
    name: ${google.application.name}
  api:
    key: ${google.api.key}
  channel:
    id: ${google.channel.id}
