spring:
  # Spring
  application:
    name: ypm

# Reverse proxy headers
server:
  forward-headers-strategy: native

# Logging
logging:
  level:
    root: info

# Swagger
springdoc:
  swagger-ui:
    urls:
      - name: general
        url: /oas/ypm.yaml
