### Get All Playlists
GET {{baseUrl}}/playlists
Cookie: JSESSIONID={{JSESSIONID_Value}}


### Get videos for a specific playlist
@playlist_id = playlist_1_id
GET {{baseUrl}}/playlists/{{playlist_id}}
Cookie: JSESSIONID={{JSESSIONID_Value}}


### Create a new playlist
POST {{baseUrl}}/playlists
Cookie: JSESSIONID={{JSESSIONID_Value}}
Content-Type: application/json

{
    "title": "Test playlist 2",
    "description": "Sample description",
    "status": "unlisted"
}


### Update playlist title
@playlist_id_to_update = playlist_1_id
PUT {{baseUrl}}/playlists/{{playlist_id_to_update}}
Cookie: JSESSIONID={{JSESSIONID_Value}}
Content-Type: application/json

{
    "title": "IDEA HTTP Playlist"
}


### Move videos from one playlist to another
@souce_playlist_id = playlist_1_id
@target_playlist_id = playlist_2_id
PUT http://localhost:8080/playlists/{{souce_playlist_id}}/{{target_playlist_id}}
Cookie: JSESSIONID={{JSESSIONID_Value}}
Content-Type: application/json

[
    "video_id"
]


### Merge playlists
PUT {{baseUrl}}/playlists
Cookie: JSESSIONID={{JSESSIONID_Value}}
Content-Type: application/json

{
    "playlistDetails": {
        "title": "Merged Playlist 1",
        "status": "private"
    },
    "playListsIds": [
        "playlist_1_id",
        "playlist_2_id"
    ],
    "deleteAfterMerge": true
}


### Delete playlist
@playlist_id_to_delete = str_val
DELETE {{baseUrl}}/playlists/{{playlist_id_to_delete}}
Cookie: JSESSIONID={{JSESSIONID_Value}}
